spring:
  application:
    name: TIKU
  
  # 数据源配置（使用环境变量）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/tiku?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root123}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false  # 生产环境关闭SQL日志
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
    open-in-view: false
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  # JSON配置
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

# 服务器配置
server:
  port: ${PORT:8080}

# JWT配置
jwt:
  secret: ${JWT_SECRET:tiku-system-jwt-secret-key-2024-very-long-secret-key-for-security-please-change-this-in-production}
  expiration: 604800000 # 7天
  header: Authorization
  prefix: Bearer 

# AI配置
ai:
  siliconflow:
    api-key: ${AI_API_KEY:}
    base-url: https://api.siliconflow.cn/v1
    model: Qwen/Qwen2.5-7B-Instruct
    temperature: 0.3
    max-tokens: 2000
    timeout: 30000
  grading:
    enabled: true
    confidence-threshold: 0.75
    retry-times: 2
    cache-enabled: true

# Actuator健康检查配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  health:
    db:
      enabled: true

# 日志配置
logging:
  level:
    root: INFO
    com.springboot.tiku: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/tiku.log
    max-size: 10MB
    max-history: 30

# 自定义配置
app:
  file:
    upload-path: ${UPLOAD_PATH:./uploads}
    temp-path: ${TEMP_PATH:./temp}
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin123}
    email: ${ADMIN_EMAIL:admin@tiku.com}

